enable-magisk-update = true   # set this to false if you do not want to receive updates for the module in magisk app

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/smmahbubhossain/ReVanced-XteNded/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config

[YouTube-ReX]
enabled = false
build-mode = "both"
excluded-patches = "'Custom branding icon YouTube' 'Custom branding name YouTube'"
included-patches = "'Add splash animation' 'MaterialYou'"
version = "auto"
patches-source = "YT-Advanced/ReX-patches"
integrations-source = "YT-Advanced/ReX-integrations"
cli-source = "j-hc/revanced-cli"
#rv-brand = "ReX"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"

[Music-ReX]
enabled = false
build-mode = "both"
excluded-patches = "'Custom branding icon YouTube Music' 'Custom branding name YouTube Music'"
patches-source = "YT-Advanced/ReX-patches"
integrations-source = "YT-Advanced/ReX-integrations"
cli-source = "j-hc/revanced-cli"
#rv-brand = "ReX"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"
arch = "both"

[Reddit]
enabled = false
apkmirror-dlurl = "https://www.apkmirror.com/apk/redditinc/reddit"

[YouTube]
enabled = true
build-mode = "both"
excluded-patches = "'Custom branding icon YouTube' 'Custom branding name YouTube'"
included-patches = "'Add splash animation' 'MaterialYou'"
version = "auto"
patches-source = "anddea/revanced-patches"
integrations-source = "anddea/revanced-integrations"
cli-source = "j-hc/revanced-cli"
rv-brand = "X"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"

[Music]
enabled = true
build-mode = "both"
excluded-patches = "'Custom branding icon YouTube Music' 'Custom branding name YouTube Music'"
patches-source = "anddea/revanced-patches"
integrations-source = "anddea/revanced-integrations"
cli-source = "j-hc/revanced-cli"
rv-brand = "X"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"
arch = "both"
